### ISSUE TITLE
JS modules

### ISSUE THREAD

**Issue by michaelb20** [mpepping/docker-cyberchef#2]
It seems like there are some problems when loading the JS modules.

![image](https://user-images.githubusercontent.com/26380375/48854970-72750280-edb3-11e8-8826-3f27e9c668b4.png)

Also the `npm run postinstall` leads to an error.

I would be happy to see some ideas for a bugfix about that!

**Comment by mpepping** [comment]
The postinstall script [was removed](https://github.com/gchq/CyberChef/commit/18a9dfffc709f8dc59748380a750b77bda7ee0b5) from the upstream `package.json`. Updated the Docker build .. thanks for reporting, @michaelb20!

**Comment by mpepping** [comment]
The "Generate PGP key" issue seems CyberChef related:
https://github.com/gchq/CyberChef/issues/305
