### ISSUE TITLE
docker hub images appear to be updating without any repo updates

### ISSUE THREAD

**Issue by webxl** [mpepping/docker-cyberchef#24]
Any ideas why these update daily? https://hub.docker.com/r/mpepping/cyberchef/tags

**Comment by mpepping** [comment]
For now we just build container images for the cyberchef master branch and latest version [on a daily basis](https://github.com/mpepping/docker-cyberchef/blob/master/.github/workflows/ci.yml#L6). Definitely something that can be improved. I'll keep this issue open for that. Thanks @webxl.

**Comment by mpepping** [comment]
Resolved via #33
