### ISSUE TITLE
Update the documentation with example docker-compose.yaml snippet

### ISSUE THREAD

**Issue by dawidgora** [mpepping/docker-cyberchef#26]
For many users, it might make sense to have an example docker-compose.yaml file added to README.md. It could speed up the process of setting up ChyberChef for them.

EDIT: I mean, I know it's a very simple one, but I know there are some people that, for example, just copy-paste things into the Portainer or similar tools.

**Comment by dawidgora** [comment]
I actually opened a PR fo this. Please have a look.

**Comment by mpepping** [comment]
Merged #27 .. thanks, @dawidgora!
