### ISSUE TITLE
Module folder not found

### ISSUE THREAD

**Issue by arckosfr** [mpepping/docker-cyberchef#3]
Hello,
It seems the module folder and all subsequent file are not generated during build.
They're in their release zip, but not in the container (and the zip inside the container don't contain modules too)

Regards

**Comment by mpepping** [comment]
Hi @arckosfr, I've checked but can't seem to pinpoint what you exactly mean by the module folder. The app seems to work and `grunt test` passes all test. Is there a specific error you're seeing?

**Comment by FatCyclone** [comment]
Same problem here, try out the "Text Encoding Brute force" module. In console you will see that https://fqdn/modules/Encodings.js is missing.

To fix it, we are manually downloading the Cyberchef zip, and unziping it to overwrite files and add the modules folder.

**Comment by mpepping** [comment]
Thanks for the input, @arckosfr! Strangely enough the modules artifacst aren't generated at build time. I'll open an issue at the CyberChef project for this.
For now, I've added @FatCyclone's work-around by adding the modules directory from the most recent release of CyberChef. Pulling `mpepping/cyberchef:latest` resolves the issue(s).

**Comment by mpepping** [comment]
#5
