### ISSUE TITLE
No build for V10.18.8

### ISSUE THREAD

**Issue by pquantin** [mpepping/docker-cyberchef#37]
It seems like the corresponding job failed: https://github.com/mpepping/docker-cyberchef/actions/runs/9474532801

**Comment by mpepping** [comment]
Will look into that, thanks!

**Comment by mpepping** [comment]
@pquantin, the build indeed failed. It is there now: `docker pull docker.io/mpepping/cyberchef:v10.18.8` .. thanks for noticing!
